name: Build APK

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.2'

    - name: Build APK
      run: gradle assembleDebug

    - name: Upload APK to S3 ToDus
      run: |
        APK_PATH="app/build/outputs/apk/debug/app-debug.apk"
        FILENAME="Seend-v0.16.apk"
        UPLOAD_URL="https://s3.todus.cu/stream/$FILENAME"
        
        curl -X PUT "$UPLOAD_URL" \
          --data-binary @"$APK_PATH" \
          --progress-bar
        
        echo "✅ APK subida: $UPLOAD_URL"
